"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useDriverPortal, driverStatusLabel } from "@/components/driver/DriverPortalShell";
import { listDriverDrafts, listQueuedDriverActions, type DriverDraft, type QueuedDriverAction } from "@/lib/driverDrafts";
import { getPhoneTrackingState, pausePhoneTracking } from "@/lib/driverPhoneTracking";

type Notice = { id: string; bookingId: string | null; title: string; body: string; createdAt: string; readAt: string | null };
type Notices = { notifications: Notice[]; pagination: { page: number; total: number; totalPages: number } };
const input = "mt-1 min-h-12 w-full rounded-xl border border-slate-300 p-3 text-base";
export default function ProfilePage() {
  const { driver, request, online, signOut, refreshNotifications } = useDriverPortal();
  const [notices, setNotices] = useState<Notices | null>(null), [page, setPage] = useState(1), [drafts, setDrafts] = useState<DriverDraft[]>([]), [actions, setActions] = useState<QueuedDriverAction[]>([]);
  const [currentPassword, setCurrentPassword] = useState(""), [password, setPassword] = useState(""), [confirmation, setConfirmation] = useState("");
  const [error, setError] = useState(""), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  const readSaved = useCallback(async () => { const [saved, queued] = await Promise.all([listDriverDrafts(driver.id), listQueuedDriverActions(driver.id)]); setDrafts(saved); setActions(queued); }, [driver.id]);
  const readNotices = useCallback(async () => { const result = await request<Notices>(`/api/driver/jobs/notifications?page=${page}&pageSize=25`); setNotices(result); }, [request, page]);
  useEffect(() => { let active = true; setNotices(null); if (online) void request<Notices>(`/api/driver/jobs/notifications?page=${page}&pageSize=25`).then(result => { if (active) setNotices(result); }).catch(failure => { if (active) setError(failure.message); }); return () => { active = false; }; }, [online, request, page]);
  useEffect(() => { void readSaved().catch(failure => setError(failure.message)); }, [readSaved]);
  async function markRead(id: string) { if (busy) return; setBusy(true); setError(""); try { await request(`/api/driver/jobs/notifications/${encodeURIComponent(id)}/read`, { method: "PATCH" }); await readNotices(); await refreshNotifications(); } catch (failure) { setError(failure instanceof Error ? failure.message : "Unable to confirm notification read."); } finally { setBusy(false); } }
  async function logout(all: boolean) {
    if (busy) return; setBusy(true); setError("");
    try { pausePhoneTracking(driver.id, "Location sharing paused for sign out."); await signOut(all); }
    catch (failure) { setError(failure instanceof Error ? failure.message : "Unable to confirm sign out. Reconnect and retry."); }
    finally { setBusy(false); }
  }
  async function changePassword(event: React.FormEvent) {
    event.preventDefault(); if (busy) return;
    if (password !== confirmation) { setError("Your new passwords do not match."); return; }
    if (password.length < 8 || new TextEncoder().encode(password).length > 72) { setError("Use at least eight characters and no more than 72 bytes."); return; }
    setBusy(true); setError("");
    try {
      pausePhoneTracking(driver.id, "Location sharing paused while changing your password.");
      const result = await request<{ requiresSignIn: boolean; message: string }>("/api/driver/auth/password", { method: "PATCH", body: JSON.stringify({ currentPassword, password }) });
      setCurrentPassword(""); setPassword(""); setConfirmation(""); setMessage(result.message);
      if (result.requiresSignIn) { for (const key of ["driverToken", "driver", "driverSessionExpiresAt"]) { try { localStorage.removeItem(key); } catch { /* Server sessions are already revoked. */ } } window.location.replace("/driver/login"); }
    } catch (failure) { setError(failure instanceof Error ? failure.message : "Unable to confirm the password update. Try signing in before retrying."); }
    finally { setBusy(false); }
  }
  const pending = drafts.filter(draft => draft.phase !== "EDITING").length + actions.length;
  return <div className="space-y-5"><h1 className="text-2xl font-bold text-[#071D49]">More</h1>
    {error && <p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{error}</p>}{message && <p role="status" className="rounded-xl bg-blue-50 p-4 text-blue-900">{message}</p>}
    <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Your account</h2><dl className="mt-3 grid grid-cols-2 gap-3 text-sm"><dt>Name</dt><dd>{driver.name}</dd><dt>Username</dt><dd className="break-all">{driver.username}</dd><dt>Email</dt><dd className="break-all">{driver.email}</dd><dt>Phone</dt><dd>{driver.phone || "Not recorded"}</dd><dt>Duty</dt><dd>{driver.onDuty ? "On duty" : "Off duty"}</dd><dt>Activity</dt><dd>{driverStatusLabel(driver.availability)}</dd><dt>Assigned van</dt><dd>{driver.vehicle?.registration || driver.vehicle?.name || "No van assigned"}</dd></dl><p className="mt-4 text-xs text-slate-500">Dispatch updates your account details and assignments in Admin → Drivers.</p></section>
    <section className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-bold">Saved on this device</h2><button onClick={() => void readSaved().catch(failure => setError(failure.message))} className="min-h-11 px-3 text-blue-700">Refresh</button></div><p className="mt-1 text-sm text-slate-600">{pending} pending updates · {drafts.filter(draft => draft.phase === "EDITING").length} editable drafts. Only the server can confirm an update.</p>{drafts.map(draft => <Link key={draft.id} href={draft.kind === "VEHICLE_CHECK" ? "/driver/vehicle" : `/driver/jobs/${encodeURIComponent(draft.bookingId || "")}`} className="mt-3 block rounded-xl border p-3"><p className="text-sm font-semibold">{driverStatusLabel(draft.kind)} · {driverStatusLabel(draft.phase)}</p><p className="text-xs text-slate-500">Saved {new Date(draft.updatedAt).toLocaleString("en-GB")}</p>{draft.reviewMessage && <p className="mt-1 text-sm text-amber-800">{draft.reviewMessage}</p>}{draft.kind === "VEHICLE_CHECK" && draft.vehicleId !== driver.vehicle?.id && <p className="mt-1 text-sm text-amber-800">This belongs to a previously assigned van. Contact dispatch; it will not be sent for your new van.</p>}</Link>)}{actions.map(action => <Link key={action.id} href={`/driver/jobs/${encodeURIComponent(action.bookingId)}`} className="mt-3 block rounded-xl border p-3"><p className="text-sm font-semibold">{driverStatusLabel(action.action)} · {driverStatusLabel(action.phase)}</p>{action.reviewMessage && <p className="text-sm text-amber-800">{action.reviewMessage}</p>}</Link>)}<p className="mt-3 text-xs text-slate-500">Saved work remains on this device after sign out and is available when the same driver signs in. Do not clear browser storage while work is pending.</p></section>
    <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Dispatch notifications</h2><p className="mt-1 text-xs text-slate-500">Notifications appear inside this portal. Phone push notifications are not enabled.</p>{!online && <p className="mt-3 text-sm text-amber-800">Reconnect to load notifications.</p>}{online && !notices && <p className="mt-3 text-sm">Loading notifications…</p>}{notices?.notifications.length === 0 && <p className="mt-3 text-sm text-slate-500">No notifications.</p>}{notices?.notifications.map(notice => <article key={notice.id} className={`mt-3 rounded-xl border p-4 ${notice.readAt ? "bg-white" : "bg-blue-50"}`}><h3 className="font-semibold">{notice.title}</h3><p className="mt-1 whitespace-pre-wrap text-sm">{notice.body}</p><p className="mt-2 text-xs text-slate-500">{new Date(notice.createdAt).toLocaleString("en-GB")}</p><div className="mt-2 flex flex-wrap gap-3">{notice.bookingId && <Link href={`/driver/jobs/${encodeURIComponent(notice.bookingId)}`} className="min-h-11 py-3 text-sm font-semibold text-blue-700">Open job</Link>}{!notice.readAt && <button disabled={!online || busy} onClick={() => void markRead(notice.id)} className="min-h-11 text-sm font-semibold text-blue-700">Mark read</button>}</div></article>)}<div className="mt-4 flex items-center justify-between"><button disabled={page <= 1 || busy} onClick={() => setPage(page - 1)} className="min-h-11 px-3 disabled:opacity-40">Previous</button><span className="text-sm">Page {page} of {Math.max(1, notices?.pagination.totalPages || 1)}</span><button disabled={!notices || page >= notices.pagination.totalPages || busy} onClick={() => setPage(page + 1)} className="min-h-11 px-3 disabled:opacity-40">Next</button></div></section>
    <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Location sharing</h2><p className="mt-2 text-sm text-slate-600">Vehicle GPS tracker integration is awaiting your chosen provider. Phone sharing is started from an active job and can pause when the phone is locked or the browser is in the background.</p><button onClick={() => { pausePhoneTracking(driver.id, "Phone sharing paused by the driver. Open the job to confirm stopping with the server."); setMessage(getPhoneTrackingState(driver.id).message); }} className="mt-3 min-h-12 rounded-xl border px-4 font-semibold">Pause phone sharing on this device</button></section>
    <form onSubmit={event => void changePassword(event)} className="space-y-4 rounded-2xl border bg-white p-5"><h2 className="font-bold">Change password</h2><p className="text-sm text-slate-600">Changing your password signs out every device. Saved drafts remain on this device.</p><label className="block text-sm font-semibold">Current password<input type="password" autoComplete="current-password" required value={currentPassword} onChange={event => setCurrentPassword(event.target.value)} className={input} /></label><label className="block text-sm font-semibold">New password<input type="password" autoComplete="new-password" minLength={8} required value={password} onChange={event => setPassword(event.target.value)} className={input} /></label><label className="block text-sm font-semibold">Confirm new password<input type="password" autoComplete="new-password" required value={confirmation} onChange={event => setConfirmation(event.target.value)} className={input} /></label><button disabled={busy || !online} className="min-h-12 w-full rounded-xl bg-blue-600 p-3 font-semibold text-white disabled:opacity-50">Update password</button></form>
    <section className="space-y-3 rounded-2xl border bg-white p-5"><h2 className="font-bold">Sign out</h2><p className="text-sm text-slate-600">Signing out pauses this device’s phone sharing. It does not cancel your job or change your duty status.</p>{pending > 0 && <p className="text-sm font-semibold text-amber-800">You have {pending} pending updates. Reconnect and confirm them before changing devices.</p>}<button disabled={busy || !online} onClick={() => void logout(false)} className="min-h-12 w-full rounded-xl border p-3 font-semibold disabled:opacity-50">Sign out this device</button><button disabled={busy || !online} onClick={() => void logout(true)} className="min-h-12 w-full rounded-xl border border-red-200 p-3 font-semibold text-red-700 disabled:opacity-50">Sign out all devices</button></section>
  </div>;
}
